version: "3.9"

services:
  promptverse:
    container_name: promptverse_app
    build:
      context: .
      dockerfile: Dockerfile
    image: promptverse:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped